### ISSUE TITLE
Is there a way to check if `prefer_gpu` has been called?

### ISSUE THREAD

**Issue by nikita-galileo** [explosion/thinc#788] opened 2022-10-13 22:07 UTC
Trying to understand how we might know if a user using spacy has called `spacy.prefer_gpu` yet. Looking through the thinc code it seems like I could almost check the value of some variable, but I'm not sure.

**Comment by polm** [comment] 2022-10-14 05:21
Duplicate of https://github.com/explosion/spaCy/discussions/11648. Please don't ask the same question in multiple places; we'll follow up in the Discussion.

**Closed by polm** 2022-10-14 05:21 UTC
